platform :ios, '9.0'
inhibit_all_warnings!
target 'QCY' do
        pod 'Masonry', '~> 1.1.0'
        pod 'AFNetworking', '~> 3.2.1'
        pod 'SDWebImage', '~> 4.4.2'
        pod 'MJExtension', '~> 3.0.15.1'
	pod 'MJRefresh', '~> 3.1.15.7'
	pod 'SDCycleScrollView', '~> 1.75'
	pod 'YYWebImage', '~> 1.0.5'
	pod 'YYText', '~> 1.0.7'
	pod 'IQKeyboardManager', '~> 6.1.1'
	pod 'SDAutoLayout', '~> 2.2.1'
	pod 'SAMKeychain', '~> 1.5.3'
	pod 'BRPickerView', '~> 2.2.1'
	pod 'MBProgressHUD', '~> 1.1.0'
	pod 'SVProgressHUD', '~> 2.2.5'
	pod 'SGPagingView', '~> 1.5.5'
	pod 'UITableView+FDTemplateLayoutCell', '~> 1.6'
	pod 'YNPageViewController', '~> 0.2.3'	
end
