platform :ios, '9.0'
inhibit_all_warnings!
target 'QCY' do
        pod 'Masonry', '~> 1.1.0'
        pod 'AFNetworking', '~> 3.2.1'
        pod 'SDWebImage', '~> 5.2.3'
        pod 'MJExtension', '~> 3.2.1'
	pod 'MJRefresh', '~> 3.1.15.7'
	pod 'SDCycleScrollView', '~> 1.80'
	pod 'YYWebImage', '~> 1.0.5'
	pod 'YYText', '~> 1.0.7'
	pod 'IQKeyboardManager', '~> 6.1.1'
	pod 'SDAutoLayout', '~> 2.2.1'
	pod 'SAMKeychain', '~> 1.5.3'
	pod 'BRPickerView', '~> 2.2.1'
	pod 'MBProgressHUD', '~> 1.1.0'
#	pod 'SVProgressHUD', '~> 2.2.5'
	pod 'SGPagingView', '~> 1.5.5'
	pod 'YNPageViewController', '~> 0.2.6'	
	pod 'XHWebImageAutoSize', '~> 1.1.2'
	pod 'TZImagePickerController', '~> 3.1.5'
#	pod 'FLAnimatedImage', '~> 1.0.12'
	pod 'YBImageBrowser', '~> 3.0.6'
	pod 'YBImageBrowser/Video'
	pod 'HXPhotoPicker', '~> 2.3.6'
	pod 'DZNEmptyDataSet', '~> 1.8.1'	
	pod 'JXCategoryView', '~> 1.3.4'
	pod 'XHLaunchAd', '~> 3.9.8'
	pod 'FMDB', '~> 2.7.5'
	pod 'SJVideoPlayer', '~> 3.2.4'
#极光推送
	pod 'JPush', '~> 3.1.2'
#识别网址的Label
	pod 'MLLabel', '~> 1.10.5'
#shareSDK
        pod 'mob_sharesdk'
        pod 'mob_sharesdk/ShareSDKUI'
	pod 'mob_sharesdk/ShareSDKPlatforms/WeChatFull'
#高德地图
	pod 'AMap3DMap-NO-IDFA'
        pod 'AMapSearch-NO-IDFA'
        pod 'AMapLocation-NO-IDFA'	
#友盟
	pod 'UMCCommon', '~> 2.1.1'
	pod 'UMCSecurityPlugins', '~> 1.0.6'
	pod 'UMCAnalytics', '~> 6.0.3'
	pod 'UMCCommonLog', '~> 1.0.0'
end
